### ISSUE TITLE
Remove unneeded callvote options

### ISSUE THREAD

**Issue by QaleQ** [MGXRace/racesow-data#14]
allready
restart
remove <player>
kick <player>

IF we get the "blocking" feature, maybe we could even think about removing the mute features. But

**Comment by Mark90** [comment]
Remove in case a player is actively annoying others with weapons (yes you can set raceghosts for this, but not everybody will bother), and kick when he persists after a remove.

**Comment by Mark90** [comment]
Apparently there exist people who use callvote kick and callvote remove on players doing boris maps, so they will be disabled anyway.
