### ISSUE TITLE
/tags command?

### ISSUE THREAD

**Issue by QaleQ** [MGXRace/racesow-data#38]
would be nice to have something like a /tags <mapname> command, that displays the tags for any given map, defaulting to current if left without arguments or so.

**Comment by Mark90** [comment]
Would rather put the tags for the current map in a 'mapinfo' command which then prints name and tags for current map and stuff. Tags for other maps can already be found with the maplist command (when it's working)

**Comment by QaleQ** [comment]
True, closing this.
